server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #    JDBC 配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #      format_sql: true
  #    database: mysql
  #    show-sql: true

  # Redis数据库索引（默认为0）
  # Redis服务器地址
  # Redis服务器连接端口
  # 连接池最大连接数（使用负值表示没有限制）
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 连接池中的最大空闲连接
  # 连接池中的最小空闲连接
  # 连接超时时间（毫秒）
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
